{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  labels:
{{ include "mattermost.labels" . | indent 4 }}
{{- end }}
