{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mattermost
  namespace: {{ .Values.namespace }}
  labels:
{{ include "mattermost.labels" . | indent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName | quote }}
      {{- if .Values.ingress.host }}
      hosts:
        - {{ .Values.ingress.host | quote }}
      {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType | quote }}
            backend:
              service:
                name: mattermost
                port:
                  number: {{ .Values.mattermost.service.port }}
    {{- else }}
    - http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType | quote }}
            backend:
              service:
                name: mattermost
                port:
                  number: {{ .Values.mattermost.service.port }}
    {{- end }}
{{- end }}

