apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mattermost
type: Opaque
stringData:
  POSTGRES_DB: mattermost
  POSTGRES_USER: mmuser
  POSTGRES_PASSWORD: mmpass
---
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-config
  namespace: mattermost
type: Opaque
stringData:
  MM_SQLSETTINGS_DRIVERNAME: postgres
  MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:mmpass@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
  MM_SERVICESETTINGS_SITEURL: ""
